## 4.1 Multivariable linear regresssion

> 지난 시간  

**linear regression을 설계하기 위해 필요한 조건(입력이 하나일 때)**
1. Hypothesis  
$$H(x)=Wx+b$$


$$W : weight, b : bias$$


2. Cost function  
$$cost(W,b) = {1\over m}\sum_{i=1}^m(H(x^{(i)})-y^{(i)})^2$$  
$$예측값 - 실제값(true)$$


3. Gradient descent algorithm  
  - cost 최적화 값 찾기   
<br>

---

**Multivariable linear regression**
  - 입력값이 3개 일 때  

1. Hypothesis
$$H(x_1,x_2,x_3) = w_1x_1+w_2x_2+w_3x_3+b$$


2. Cost function
$$cost(W,b) = {1\over m}\sum_{i=1}^m(H(x_1^{(i)},x_2^{(i)},x_3^{(i)})-y^{(i)})^2$$  


**Hypothesis using matrix**

$$w_1x_1+w_2x_2+w_3x_3+...+w_nx_n$$  
$$\left[ \begin{array}{ccc}
x_{11} & x_{12} & x_{13} \\
x_{21} & x_{22} & x_{23} \\
x_{31} & x_{32} & x_{33} \\
x_{41} & x_{42} & x_{43} \\
x_{51} & x_{52} & x_{53} \\ \end{array} \right]  
*  \left[ \begin{array}{c}
        w_{1} \\
        w_{2} \\
        w_{3} \\ \end{array} \right] = \left[ \begin{array}{c}
x_{11}w_1 + x_{12}w_2 + x_{13}w_3 \\
x_{21}w_1 + x_{22}w_2 + x_{23}w_3 \\
x_{31}w_1 + x_{32}w_2 + x_{33}w_3 \\
x_{41}w_1 + x_{42}w_2 + x_{43}w_3 \\
x_{51}w_1 + x_{52}w_2 + x_{53}w_3 \\ \end{array} \right]$$  

<br>
<br>
$$H(x) = XW$$

- [5,3] * [3,1] = [5,1]  
- <u>[5,3]에서 5는 인스턴스 개수, 3은 variable 개수</u>


- [n,**3**] * [**3**,**1**] = [n,**1**]  
    - n : 여러 개 들어올 수 있음(넘파이에서는 -1, 텐서플로에서는 None으로 표현)  


**WX vs XW **  
1. Lecture(theory)   
$$H(x) = Wx+b$$


2. Implementation(TensorFlow)  
$$H(x)=XW$$


---

## lab 4.1 multi-variable linear regression 구현

**lab-04-1-multi_variable_linear_regression**

In [14]:
import tensorflow as tf

tf.set_random_seed(777) # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# weight과 bias는 하나의 값 -> [1]
w1 = tf.Variable(tf.random_normal([1]),name='weight1') # 변수 생성
w2 = tf.Variable(tf.random_normal([1]),name='wegith2')
w3 = tf.Variable(tf.random_normal([1]),name='weight3')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [15]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b # H(x1,x2,x3) = x1w1+x2w2+x3w3

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize: Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# 학습
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPredict:\n", hy_val)


0 Cost:  8935.937 
Predict:
 [70.81859  81.668625 82.52838  88.76229  61.929752]
10 Cost:  5.656308 
Predict:
 [154.40627 182.1517  181.52725 196.57054 138.57646]
20 Cost:  5.545729 
Predict:
 [154.65024 182.46185 181.82408 196.89473 138.81647]
30 Cost:  5.517083 
Predict:
 [154.64207 182.4689  181.82227 196.89368 138.82524]
40 Cost:  5.488579 
Predict:
 [154.63316 182.47502 181.81955 196.89166 138.8333 ]
50 Cost:  5.4602804 
Predict:
 [154.62431 182.4811  181.81683 196.88965 138.84134]
60 Cost:  5.4320717 
Predict:
 [154.61545 182.48718 181.81412 196.88765 138.84935]
70 Cost:  5.4040384 
Predict:
 [154.60663 182.49323 181.81142 196.88564 138.85736]
80 Cost:  5.376172 
Predict:
 [154.59782 182.49928 181.80875 196.88365 138.86533]
90 Cost:  5.348427 
Predict:
 [154.58905 182.50531 181.80606 196.88165 138.87329]
100 Cost:  5.3208437 
Predict:
 [154.5803  182.51134 181.80339 196.87967 138.88123]
110 Cost:  5.293374 
Predict:
 [154.57153 182.5173  181.80069 196.87767 138.88913]
120 Cost:  

1040 Cost:  3.2946332 
Predict:
 [153.85472 183.0092  181.58165 196.71443 139.53873]
1050 Cost:  3.2781491 
Predict:
 [153.84796 183.01384 181.57959 196.71289 139.54488]
1060 Cost:  3.261741 
Predict:
 [153.84122 183.01848 181.57751 196.71135 139.551  ]
1070 Cost:  3.245441 
Predict:
 [153.83447 183.02309 181.57545 196.70981 139.55708]
1080 Cost:  3.2291915 
Predict:
 [153.82777 183.02771 181.5734  196.70827 139.56319]
1090 Cost:  3.2130675 
Predict:
 [153.82106 183.0323  181.57137 196.70674 139.56924]
1100 Cost:  3.1970456 
Predict:
 [153.8144  183.03687 181.56932 196.70522 139.5753 ]
1110 Cost:  3.181059 
Predict:
 [153.80774 183.04144 181.56728 196.70369 139.58134]
1120 Cost:  3.165196 
Predict:
 [153.80112 183.04602 181.56528 196.70218 139.58737]
1130 Cost:  3.1494017 
Predict:
 [153.79448 183.05055 181.56323 196.70067 139.59337]
1140 Cost:  3.1337245 
Predict:
 [153.78789 183.05507 181.56122 196.69914 139.59935]
1150 Cost:  3.1181064 
Predict:
 [153.78131 183.0596  181.55922 196.6

>행렬 이용

**lab-04-2-multi_variable_linear_regression**

$$\left[ \begin{array}{ccc}
x_{1} & x_{2} & x_{3} \\ \end{array} \right]  
*  \left[ \begin{array}{c}
        w_{1} \\
        w_{2} \\
        w_{3} \\ \end{array} \right] = \left[ \begin{array}{c}
x_{1}w_1 + x_{2}w_2 + x_{3}w_3 \\ \end{array} \right]$$  

<br>
<br>
$$H(x) = XW$$

In [16]:
tf.set_random_seed(777)

x_data = [[73., 80., 75.],
         [93., 88., 93.],
         [89., 91., 90.],
         [96., 98., 100.],
         [73., 66., 70.]]

y_data = [[152.],
         [185.],
         [180.],
         [196.],
         [142.]]

### 여기 행렬 이용해서 간단하게 구현 ###
# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None,3]) # x1,x2,x3(각 element) 3개라서 3, 앞에 None은 필요에 따라 x를 추가할 수 있기 때문에 n개의 데이터를 가지고 있음을 의미
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

# Hypothesis
hypothesis = tf.matmul(X,W)+b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis-Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initialies global variables in the grpah
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 41876.15 
Prediction:
 [[-27.637243]
 [-35.183983]
 [-33.525547]
 [-38.159466]
 [-25.94763 ]]
10 Cost: 2.776191 
Prediction:
 [[153.37672]
 [182.39215]
 [180.8503 ]
 [195.29126]
 [140.01018]]
20 Cost: 2.381392 
Prediction:
 [[153.91873]
 [183.05437]
 [181.49716]
 [195.99649]
 [140.51729]]
30 Cost: 2.3699558 
Prediction:
 [[153.91467]
 [183.06026]
 [181.49734]
 [195.99751]
 [140.5238 ]]
40 Cost: 2.3586292 
Prediction:
 [[153.90898]
 [183.06412]
 [181.49557]
 [195.9964 ]
 [140.52876]]
50 Cost: 2.3473191 
Prediction:
 [[153.9033 ]
 [183.06802]
 [181.49382]
 [195.9953 ]
 [140.53372]]
60 Cost: 2.336104 
Prediction:
 [[153.89764]
 [183.07188]
 [181.49207]
 [195.99417]
 [140.53865]]
70 Cost: 2.3249512 
Prediction:
 [[153.892  ]
 [183.07573]
 [181.49031]
 [195.99306]
 [140.54356]]
80 Cost: 2.3138375 
Prediction:
 [[153.88637]
 [183.07959]
 [181.48859]
 [195.99197]
 [140.5485 ]]
90 Cost: 2.3027763 
Prediction:
 [[153.88074]
 [183.08342]
 [181.48682]
 [195.99088]
 [140.55338]]
100 Cost: 

 [[153.4767 ]
 [183.35912]
 [181.36137]
 [195.91284]
 [140.9045 ]]
900 Cost: 1.579705 
Prediction:
 [[153.4722 ]
 [183.36221]
 [181.35995]
 [195.91199]
 [140.9084 ]]
910 Cost: 1.572598 
Prediction:
 [[153.46767]
 [183.36528]
 [181.35855]
 [195.91112]
 [140.91231]]
920 Cost: 1.5655235 
Prediction:
 [[153.46318]
 [183.36838]
 [181.35716]
 [195.9103 ]
 [140.91621]]
930 Cost: 1.5585163 
Prediction:
 [[153.45868]
 [183.3714 ]
 [181.35576]
 [195.90941]
 [140.92009]]
940 Cost: 1.5515311 
Prediction:
 [[153.45422]
 [183.37447]
 [181.35437]
 [195.90857]
 [140.92397]]
950 Cost: 1.5445734 
Prediction:
 [[153.44974]
 [183.3775 ]
 [181.35298]
 [195.90773]
 [140.92783]]
960 Cost: 1.5376605 
Prediction:
 [[153.44531]
 [183.38055]
 [181.3516 ]
 [195.90688]
 [140.93169]]
970 Cost: 1.5307829 
Prediction:
 [[153.44086]
 [183.38358]
 [181.35022]
 [195.90602]
 [140.93553]]
980 Cost: 1.523947 
Prediction:
 [[153.43643]
 [183.3866 ]
 [181.34885]
 [195.9052 ]
 [140.93936]]
990 Cost: 1.5171613 
Prediction:
 [[

1750 Cost: 1.0939234 
Prediction:
 [[153.12862]
 [183.59639]
 [181.25294]
 [195.84785]
 [141.20457]]
1760 Cost: 1.0894284 
Prediction:
 [[153.12503]
 [183.59885]
 [181.25183]
 [195.84718]
 [141.20767]]
1770 Cost: 1.0849551 
Prediction:
 [[153.12143]
 [183.6013 ]
 [181.25073]
 [195.84653]
 [141.21074]]
1780 Cost: 1.0805013 
Prediction:
 [[153.11786]
 [183.60373]
 [181.24959]
 [195.84587]
 [141.2138 ]]
1790 Cost: 1.0760837 
Prediction:
 [[153.1143 ]
 [183.60616]
 [181.24849]
 [195.84523]
 [141.21689]]
1800 Cost: 1.0716625 
Prediction:
 [[153.11073]
 [183.6086 ]
 [181.24736]
 [195.84457]
 [141.21992]]
1810 Cost: 1.0672978 
Prediction:
 [[153.10718]
 [183.61101]
 [181.24628]
 [195.84395]
 [141.22296]]
1820 Cost: 1.0629333 
Prediction:
 [[153.10362]
 [183.6134 ]
 [181.24515]
 [195.84328]
 [141.226  ]]
1830 Cost: 1.0586236 
Prediction:
 [[153.10011]
 [183.6158 ]
 [181.24405]
 [195.84264]
 [141.229  ]]
1840 Cost: 1.0543149 
Prediction:
 [[153.0966 ]
 [183.61821]
 [181.24297]
 [195.842  ]
 [14

## lab 4.2 TensorFlow로 파일에서 데이터 읽어오기

**lab-04-3-file_input_linear_regression**

In [17]:
import pandas as pd
data1 = pd.read_csv('data-01-test-score.csv')
data1

73  80   75  152
0   93  88   93  185
1   89  91   90  180
2   96  98  100  196
3   73  66   70  142
4   53  46   55  101
5   69  74   77  149
6   47  56   60  115
7   87  79   90  175
8   79  70   88  164
9   69  70   73  141
10  70  65   74  141
11  93  95   91  184
12  79  80   73  152
13  70  73   78  148
14  93  89   96  192
15  78  75   68  147
16  81  90   93  183
17  88  92   86  177
18  78  83   77  159
19  82  86   90  177
20  86  82   89  175
21  78  83   85  175
22  76  83   71  149
23  96  93   95  192

**Slicing**  
(참고 : https://wikidocs.net/14, http://aikorea.org/cs231n/python-numpy-tutorial/)

In [18]:
nums = range(5) # range is a built-in function that creates a list of integers
nums = [0,1,2,3,4]
print(nums) # Prints  "[0,1,2,3,4]"
print(nums[2:4]) # Get a slice from index 2 to 4 (exclusive); prints "[2,3]"
                # 2번째, 3번째 출력

print(nums[2:]) # Get a slice from index 2 to the end; prints "[2,3,4]"
print(nums[:2]) # Get a lslice from the start to index 2 (exclusive); prints "[0,1]"
print(nums[:]) # Get a slice of the whole list; prints "[0,1,2,3,4]"

print(nums[:-1]) # Slice indices can be negatives; prints "[0,1,2,3]"

nums[2:4] = [8,9] # 2번째, 3번째
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


**Indexing, Slicing, Iterating(넘파이)**  
- Arrays can be indexed, sliced, iterated much like lists and other sequence types in Python  
- As with Python lists, slicing in Numpy can be accomplished with the colon(:) syntax  
- Colon instance(:) can be replaced with dots(...)

In [19]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a[1:3])
print(a[-1])
a[0:2]=9
print(a)

print("==================")

b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b[:,1]) # 각 행마다 2번째 인덱스

print(b[-1])
print(b[-1,:])
print(b[-1,...])

print(b[0:2,:])

[2 3]
5
[9 9 3 4 5]
[ 2  6 10]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]


In [20]:
import numpy as np
tf.set_random_seed(777)

# 차례대로 파일 이름, ,로 구분, 파일의 데이터 타입도 정함
# 단점은 파일의 데이터 타입이 모두 같아야 함
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1] # 0:-1 : 마지막 한 열을 제외한 모든 데이터
y_data = xy[:, [-1]]

# Make sure the shape and data are Ok(데이터 확인)
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [21]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight') # 3은 들어오는 값, x 값
b = tf.Variable(tf.random_normal([1]), name='bias') # 출력 값 즉, y가 하나 밖에 없음

# Hypothesis
hypothesis = tf.matmul(X,W) + b

# Simplified cost/oss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 58960.94 
Prediction:
 [[-72.7976  ]
 [-91.22891 ]
 [-87.84398 ]
 [-94.84072 ]
 [-71.60799 ]
 [-52.78259 ]
 [-69.353226]
 [-48.81958 ]
 [-85.547165]
 [-78.30617 ]
 [-68.79254 ]
 [-69.42944 ]
 [-91.43733 ]
 [-77.561264]
 [-70.20735 ]
 [-91.54081 ]
 [-76.03785 ]
 [-81.466736]
 [-86.73227 ]
 [-77.24507 ]
 [-81.81449 ]
 [-84.80166 ]
 [-77.931984]
 [-75.08476 ]
 [-94.13987 ]]
10 Cost: 13.449292 
Prediction:
 [[153.90308]
 [181.26318]
 [180.63695]
 [197.55872]
 [136.21356]
 [100.44311]
 [149.51765]
 [113.43699]
 [169.12453]
 [157.59082]
 [142.08041]
 [138.50534]
 [185.93753]
 [153.01498]
 [149.67276]
 [184.97601]
 [143.55753]
 [181.19745]
 [177.70157]
 [159.35876]
 [174.84787]
 [170.83453]
 [166.77283]
 [153.47641]
 [188.26218]]
20 Cost: 10.596188 
Prediction:
 [[155.45886 ]
 [183.15146 ]
 [182.48775 ]
 [199.57794 ]
 [137.6553  ]
 [101.513664]
 [151.02927 ]
 [114.55723 ]
 [170.89786 ]
 [159.24289 ]
 [143.53859 ]
 [139.95258 ]
 [187.84634 ]
 [154.5979  ]
 [151.19446 ]
 [186.89386 ]
 [

240 Cost: 9.809906 
Prediction:
 [[155.24843]
 [183.28447]
 [182.41386]
 [199.57167]
 [137.79141]
 [101.7735 ]
 [151.02652]
 [114.54653]
 [171.20232]
 [159.72331]
 [143.57481]
 [140.18701]
 [187.70102]
 [154.39714]
 [151.25755]
 [187.06384]
 [144.90498]
 [182.96362]
 [179.30818]
 [160.76662]
 [176.64766]
 [172.78069]
 [168.43236]
 [154.66226]
 [190.25703]]
250 Cost: 9.777539 
Prediction:
 [[155.23883]
 [183.2897 ]
 [182.41013]
 [199.57077]
 [137.79692]
 [101.78445]
 [151.02588]
 [114.54565]
 [171.21497]
 [159.74356]
 [143.57593]
 [140.19672]
 [187.69418]
 [154.38803]
 [151.25977]
 [187.07063]
 [144.89764]
 [182.961  ]
 [179.29858]
 [160.75679]
 [176.6482 ]
 [172.78763]
 [168.43054]
 [154.6456 ]
 [190.25833]]
260 Cost: 9.745449 
Prediction:
 [[155.22928 ]
 [183.2949  ]
 [182.40639 ]
 [199.56989 ]
 [137.80243 ]
 [101.795334]
 [151.02527 ]
 [114.54472 ]
 [171.22757 ]
 [159.76376 ]
 [143.57703 ]
 [140.20638 ]
 [187.68738 ]
 [154.37897 ]
 [151.26198 ]
 [187.0774  ]
 [144.89032 ]
 [182.95837

480 Cost: 9.103906 
Prediction:
 [[155.02873]
 [183.40466]
 [182.32834]
 [199.551  ]
 [137.91873]
 [102.02397]
 [151.0109 ]
 [114.52341]
 [171.49222]
 [160.1863 ]
 [143.59988]
 [140.40903]
 [187.54541]
 [154.19019]
 [151.30725]
 [187.2193 ]
 [144.7392 ]
 [182.9016 ]
 [179.08914]
 [160.54216]
 [176.65875]
 [172.93948]
 [168.38972]
 [154.28204]
 [190.28725]]
490 Cost: 9.077495 
Prediction:
 [[155.02003 ]
 [183.40942 ]
 [182.32498 ]
 [199.55017 ]
 [137.9238  ]
 [102.03387 ]
 [151.01022 ]
 [114.522385]
 [171.5037  ]
 [160.20456 ]
 [143.60086 ]
 [140.41779 ]
 [187.53929 ]
 [154.18207 ]
 [151.30917 ]
 [187.22545 ]
 [144.73276 ]
 [182.89905 ]
 [179.08052 ]
 [160.5333  ]
 [176.65915 ]
 [172.94576 ]
 [168.38799 ]
 [154.26706 ]
 [190.28848 ]]
500 Cost: 9.051284 
Prediction:
 [[155.01138]
 [183.4142 ]
 [182.32161]
 [199.54933]
 [137.92888]
 [102.04374]
 [151.00954]
 [114.52136]
 [171.51512]
 [160.22275]
 [143.60182]
 [140.42653]
 [187.5332 ]
 [154.174  ]
 [151.31108]
 [187.23157]
 [144.72633]
 [1

780 Cost: 8.400438 
Prediction:
 [[154.78276]
 [183.54071]
 [182.23344]
 [199.52718]
 [138.06409]
 [102.30415]
 [150.99007]
 [114.49106]
 [171.81659]
 [160.70102]
 [143.62686]
 [140.65654]
 [187.37375]
 [153.96301]
 [151.35959]
 [187.39319]
 [144.56033]
 [182.82678]
 [178.84637]
 [160.2926 ]
 [176.66806]
 [173.11697]
 [168.33934]
 [153.86023]
 [190.32315]]
790 Cost: 8.379896 
Prediction:
 [[154.77509]
 [183.545  ]
 [182.2305 ]
 [199.52643]
 [138.0687 ]
 [102.31291]
 [150.98936]
 [114.48993]
 [171.82675]
 [160.71707]
 [143.62769]
 [140.66428]
 [187.36844]
 [153.956  ]
 [151.36118]
 [187.39864]
 [144.55487]
 [182.82434]
 [178.83884]
 [160.28485]
 [176.6683 ]
 [173.12254]
 [168.33774]
 [153.84714]
 [190.32433]]
800 Cost: 8.359539 
Prediction:
 [[154.76743 ]
 [183.54926 ]
 [182.22757 ]
 [199.52567 ]
 [138.07329 ]
 [102.32164 ]
 [150.98865 ]
 [114.488785]
 [171.83685 ]
 [160.73302 ]
 [143.62851 ]
 [140.67195 ]
 [187.36313 ]
 [153.949   ]
 [151.36275 ]
 [187.40405 ]
 [144.54944 ]
 [182.8219 

1030 Cost: 7.9353814 
Prediction:
 [[154.5996 ]
 [183.64325]
 [182.16345]
 [199.50893]
 [138.17464]
 [102.51268]
 [150.97194]
 [114.46185]
 [172.05806]
 [161.08157]
 [143.64607]
 [140.84009]
 [187.24794]
 [153.79741]
 [151.39601]
 [187.52263]
 [144.43245]
 [182.76685]
 [178.66753]
 [160.10814]
 [176.67256]
 [173.24902]
 [168.29976]
 [153.54918]
 [190.35158]]
1040 Cost: 7.918699 
Prediction:
 [[154.59264 ]
 [183.64717 ]
 [182.16081 ]
 [199.50821 ]
 [138.17888 ]
 [102.52058 ]
 [150.9712  ]
 [114.460655]
 [172.06721 ]
 [161.09596 ]
 [143.64677 ]
 [140.84703 ]
 [187.24321 ]
 [153.79118 ]
 [151.39732 ]
 [187.52754 ]
 [144.4277  ]
 [182.76448 ]
 [178.66078 ]
 [160.10115 ]
 [176.67268 ]
 [173.25401 ]
 [168.29822 ]
 [153.53743 ]
 [190.35268 ]]
1050 Cost: 7.902195 
Prediction:
 [[154.58572 ]
 [183.65106 ]
 [182.15817 ]
 [199.5075  ]
 [138.1831  ]
 [102.528465]
 [150.97046 ]
 [114.45946 ]
 [172.07632 ]
 [161.11026 ]
 [143.64749 ]
 [140.85394 ]
 [187.2385  ]
 [153.785   ]
 [151.39865 ]
 [187.5324

1300 Cost: 7.530918 
Prediction:
 [[154.42157]
 [183.74405]
 [182.09605]
 [199.49066]
 [138.2842 ]
 [102.71518]
 [150.95183]
 [114.42866]
 [172.29256]
 [161.44872]
 [143.66393]
 [141.01768]
 [187.12758]
 [153.63985]
 [151.42891]
 [187.64833]
 [144.31319]
 [182.70459]
 [178.49556]
 [159.93016]
 [176.67458]
 [173.37715]
 [168.25932]
 [153.24977]
 [190.38077]]
1310 Cost: 7.5176005 
Prediction:
 [[154.41534 ]
 [183.7476  ]
 [182.09372 ]
 [199.49002 ]
 [138.28809 ]
 [102.72227 ]
 [150.95108 ]
 [114.427414]
 [172.30078 ]
 [161.46152 ]
 [143.66454 ]
 [141.02388 ]
 [187.1234  ]
 [153.6344  ]
 [151.43002 ]
 [187.65271 ]
 [144.30911 ]
 [182.70233 ]
 [178.48958 ]
 [159.92395 ]
 [176.67462 ]
 [173.38164 ]
 [168.25787 ]
 [153.23935 ]
 [190.38184 ]]
1320 Cost: 7.5043983 
Prediction:
 [[154.40913]
 [183.75113]
 [182.09137]
 [199.48935]
 [138.29193]
 [102.72931]
 [150.95032]
 [114.42614]
 [172.30893]
 [161.47424]
 [143.66513]
 [141.03003]
 [187.11923]
 [153.62897]
 [151.43109]
 [187.65707]
 [144.30507

1570 Cost: 7.207565 
Prediction:
 [[154.26196]
 [183.83551]
 [182.03627]
 [199.47382]
 [138.38448]
 [102.89658]
 [150.93141]
 [114.39427]
 [172.50269]
 [161.77528]
 [143.67912]
 [141.17615]
 [187.0215 ]
 [153.50182]
 [151.45604]
 [187.76091]
 [144.2111 ]
 [182.64494]
 [178.34312]
 [159.77184]
 [176.67418]
 [173.49187]
 [168.22118]
 [152.9841 ]
 [190.40846]]
1580 Cost: 7.196925 
Prediction:
 [[154.25638]
 [183.83873]
 [182.03418]
 [199.47322]
 [138.38803]
 [102.90293]
 [150.93066]
 [114.39298]
 [172.51004]
 [161.78667]
 [143.67966]
 [141.18169]
 [187.01784]
 [153.49706]
 [151.45695]
 [187.76485]
 [144.20763]
 [182.64278]
 [178.33783]
 [159.76633]
 [176.67413]
 [173.49588]
 [168.2198 ]
 [152.97485]
 [190.40947]]
1590 Cost: 7.1863575 
Prediction:
 [[154.25081]
 [183.84193]
 [182.0321 ]
 [199.4726 ]
 [138.39154]
 [102.90925]
 [150.92989]
 [114.39169]
 [172.51733]
 [161.798  ]
 [143.68015]
 [141.18718]
 [187.01416]
 [153.4923 ]
 [151.45784]
 [187.76877]
 [144.20415]
 [182.64061]
 [178.33255

1840 Cost: 6.9486833 
Prediction:
 [[154.1188 ]
 [183.91856]
 [181.98317]
 [199.45825]
 [138.4763 ]
 [103.05915]
 [150.9109 ]
 [114.35912]
 [172.69102]
 [162.06584]
 [143.69203]
 [141.3176 ]
 [186.92805]
 [153.38103]
 [151.4782 ]
 [187.86183]
 [144.12398]
 [182.58788]
 [178.20804]
 [159.63098]
 [176.67177]
 [173.59459]
 [168.18521]
 [152.74838]
 [190.43468]]
1850 Cost: 6.940149 
Prediction:
 [[154.1138  ]
 [183.92148 ]
 [181.98132 ]
 [199.4577  ]
 [138.47955 ]
 [103.064835]
 [150.91013 ]
 [114.35783 ]
 [172.6976  ]
 [162.07596 ]
 [143.69247 ]
 [141.32253 ]
 [186.9248  ]
 [153.37685 ]
 [151.47894 ]
 [187.86536 ]
 [144.12103 ]
 [182.58582 ]
 [178.20334 ]
 [159.62607 ]
 [176.67163 ]
 [173.59818 ]
 [168.18393 ]
 [152.74019 ]
 [190.43562 ]]
1860 Cost: 6.93171 
Prediction:
 [[154.10881 ]
 [183.9244  ]
 [181.97949 ]
 [199.45715 ]
 [138.48279 ]
 [103.070496]
 [150.90936 ]
 [114.35651 ]
 [172.70416 ]
 [162.08603 ]
 [143.6929  ]
 [141.32745 ]
 [186.92159 ]
 [153.37271 ]
 [151.47966 ]
 [187.86887

In [22]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


Your score will be  [[181.21455]]
Other scores will be  [[181.3787 ]
 [177.94292]]


**lab-04-4-tf_reader_linear_regression**

<img src='https://t1.daumcdn.net/cfile/tistory/99C6EF415AA8AF5C1C'>
<img src='https://lh3.googleusercontent.com/proxy/m_Wk5evd2TKEuYyDjZiTe4rig1sgjq6ZRPMgo0X9wXmt-xI1hB2CVaJGMNpOlabaV763Z6PnBAfJjsK25ridhHo4edJFp-PosjbvXtysV24MCoyMDHKR0ObjkLB1UVlgeOBwmi-aYNjplYVuCjMkWJLchMziL4zRSrXln8krQzKoTVhbUDDaA6KAFXd2B7t2aiV4sHQJoqeOWqAqbLhSqhyyHBWbOYAGmiJxo91aFAMWZIxzvVYvfpKTokx2uuCiYwNK1bhEohWIhSq3TfPNDmcMs0utofAGlQ'>

In [23]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) 
                  # x data     y data
# tf.train.batch 함수가 배치로 묶어서 리턴을 하는 함수인데, batch로 묶고자 하는 tensor 들을 인자로 준 다음에, 
# batch_size (한번에 묶어서 리턴하고자 하는 텐서들의 개수)를 정해주면 된다.
# 출처: https://bcho.tistory.com/1170 [조대협의 블로그]
                 

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base

340 Cost:  48.666054 
Prediction:
 [[159.34872]
 [182.01097]
 [184.4174 ]
 [198.90549]
 [138.00804]
 [ 97.56411]
 [148.61153]
 [110.08546]
 [165.48491]
 [148.0882 ]]
350 Cost:  48.2357 
Prediction:
 [[159.32126 ]
 [182.0254  ]
 [184.40598 ]
 [198.90768 ]
 [138.01877 ]
 [ 97.600136]
 [148.62161 ]
 [110.10332 ]
 [165.52728 ]
 [148.16402 ]]
360 Cost:  47.809345 
Prediction:
 [[159.29393]
 [182.03978]
 [184.3946 ]
 [198.90985]
 [138.02946]
 [ 97.63602]
 [148.63162]
 [110.1211 ]
 [165.56946]
 [148.2395 ]]
370 Cost:  47.38697 
Prediction:
 [[159.26671 ]
 [182.0541  ]
 [184.3833  ]
 [198.91203 ]
 [138.0401  ]
 [ 97.671715]
 [148.64162 ]
 [110.1388  ]
 [165.61145 ]
 [148.31465 ]]
380 Cost:  46.968586 
Prediction:
 [[159.23962]
 [182.06834]
 [184.37202]
 [198.9142 ]
 [138.0507 ]
 [ 97.70726]
 [148.65157]
 [110.15643]
 [165.65326]
 [148.38943]]
390 Cost:  46.55413 
Prediction:
 [[159.21266]
 [182.08252]
 [184.36082]
 [198.91635]
 [138.06123]
 [ 97.74264]
 [148.66147]
 [110.17398]
 [165.69487]
 [

830 Cost:  31.715729 
Prediction:
 [[158.14148 ]
 [182.64517 ]
 [183.91492 ]
 [199.00229 ]
 [138.47855 ]
 [ 99.148346]
 [149.05658 ]
 [110.874664]
 [167.3482  ]
 [151.4241  ]]
840 Cost:  31.445446 
Prediction:
 [[158.11955]
 [182.65666]
 [183.90578]
 [199.00404]
 [138.48705]
 [ 99.17709]
 [149.0647 ]
 [110.88906]
 [167.382  ]
 [151.48468]]
850 Cost:  31.177692 
Prediction:
 [[158.09776]
 [182.6681 ]
 [183.8967 ]
 [199.00583]
 [138.49551]
 [ 99.20571]
 [149.0728 ]
 [110.90341]
 [167.41568]
 [151.545  ]]
860 Cost:  30.91248 
Prediction:
 [[158.07607 ]
 [182.6795  ]
 [183.88766 ]
 [199.00758 ]
 [138.50394 ]
 [ 99.2342  ]
 [149.08086 ]
 [110.917694]
 [167.44919 ]
 [151.60504 ]]
870 Cost:  30.64982 
Prediction:
 [[158.05444]
 [182.69081]
 [183.87865]
 [199.00931]
 [138.5123 ]
 [ 99.26255]
 [149.08885]
 [110.93191]
 [167.48253]
 [151.6648 ]]
880 Cost:  30.38963 
Prediction:
 [[158.03294 ]
 [182.70212 ]
 [183.86969 ]
 [199.01106 ]
 [138.52066 ]
 [ 99.29079 ]
 [149.09685 ]
 [110.946075]
 [167.

1330 Cost:  20.92229 
Prediction:
 [[157.16107]
 [183.1586 ]
 [183.50592]
 [199.08183]
 [138.85738]
 [100.43518]
 [149.42198]
 [111.52313]
 [168.86179]
 [154.1376 ]]
1340 Cost:  20.754929 
Prediction:
 [[157.14369]
 [183.1677 ]
 [183.49869]
 [199.08325]
 [138.86407]
 [100.45801]
 [149.4285 ]
 [111.5347 ]
 [168.88864]
 [154.18579]]
1350 Cost:  20.589146 
Prediction:
 [[157.12637 ]
 [183.17673 ]
 [183.49144 ]
 [199.08466 ]
 [138.87073 ]
 [100.480736]
 [149.43498 ]
 [111.546234]
 [168.91536 ]
 [154.23375 ]]
1360 Cost:  20.424942 
Prediction:
 [[157.10915]
 [183.18575]
 [183.48427]
 [199.08609]
 [138.87735]
 [100.50335]
 [149.44145]
 [111.55771]
 [168.94199]
 [154.28151]]
1370 Cost:  20.262333 
Prediction:
 [[157.092  ]
 [183.19472]
 [183.47708]
 [199.0875 ]
 [138.88394]
 [100.52588]
 [149.44789]
 [111.56915]
 [168.96846]
 [154.32903]]
1380 Cost:  20.10136 
Prediction:
 [[157.0749 ]
 [183.20363]
 [183.46994]
 [199.08888]
 [138.89049]
 [100.54827]
 [149.4543 ]
 [111.58052]
 [168.99481]
 [15

1840 Cost:  14.15285 
Prediction:
 [[156.36908]
 [183.57185]
 [183.17473]
 [199.14696]
 [139.1604 ]
 [101.47498]
 [149.72078]
 [112.05391]
 [170.08488]
 [156.33374]]
1850 Cost:  14.0508175 
Prediction:
 [[156.35535]
 [183.57903]
 [183.16898]
 [199.1481 ]
 [139.16565]
 [101.49303]
 [149.72601]
 [112.0632 ]
 [170.10611]
 [156.37187]]
1860 Cost:  13.949793 
Prediction:
 [[156.34167 ]
 [183.58615 ]
 [183.16325 ]
 [199.14923 ]
 [139.17084 ]
 [101.51098 ]
 [149.73122 ]
 [112.072426]
 [170.12724 ]
 [156.40984 ]]
1870 Cost:  13.84978 
Prediction:
 [[156.32806]
 [183.59322]
 [183.15755]
 [199.15036]
 [139.17601]
 [101.52885]
 [149.73637]
 [112.08161]
 [170.14825]
 [156.44762]]
1880 Cost:  13.750692 
Prediction:
 [[156.31451 ]
 [183.60028 ]
 [183.15187 ]
 [199.15149 ]
 [139.18117 ]
 [101.54664 ]
 [149.74153 ]
 [112.090775]
 [170.16917 ]
 [156.48524 ]]
1890 Cost:  13.652562 
Prediction:
 [[156.30104]
 [183.6073 ]
 [183.14622]
 [199.15262]
 [139.1863 ]
 [101.56436]
 [149.74667]
 [112.09989]
 [170.

In [24]:
# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[174.10161]]
Other scores will be  [[162.82405]
 [186.37091]]


**shuffle_batch**  
- min_after_decueue defines how big a buffer we will randomly sample from -- bigger means better shuffling but slower start up and more memory used.  
- capacity must be larger than min_after_dequeue and the amount larger determines the maximum we will prefetch.  
- Recommendation : min_after_dequeue + (num_threads + a small safety margin) * batch_size

In [25]:
min_after_dequeue = 10000
capacity = min_after_dequeue + 3*batch_size
example_batch, label_batch = tf.train.shuffle_batch([example,label],
                                                   batch_size=batch_size,
                                                   capacity=capacity,
                                                   min_after_dequeue=min_after_dequeue)

NameError: name 'batch_size' is not defined