## Tensor Manimpulation

In [3]:
import tensorflow as tf
import numpy as np
import pprint

tf.set_random_seed(777) # for reproducibility
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

## Simple Array

In [4]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1]) # t[-1] : 제일 마지막 
print(t[2:5], t[4:-1]) # slice
print(t[:2],t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## 2D Array

In [5]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape, 4행 3열

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Shape, Rank, Axis

In [8]:
t = tf.constant([1,2,3,4]) # 상수 텐서 생성
tf.shape(t).eval()

array([4])

In [9]:
print(tf.shape(t))

Tensor("Shape_4:0", shape=(1,), dtype=int32)


In [10]:
t = tf.constant([[1,2],[3,4]]) 
tf.shape(t).eval()

array([2, 2])

- '['이 몇개 있는지 => rank 개수  
- rank가 2개면 shape은 (?,?)  
    - [1,2] 안에 2개 -> (?,2)  
    - [1,2], [3,4] 2개 -> (2,2)

In [11]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

1. rank = 4  


2. rank가 4니깐 shape은 (?,?,?,?)  
    - [1,2,3,4] 안에 4개 있음 -> (?,?,?,4)  
    - [1,2,3,4] 전체를 x, [5,6,7,8] 전체를 y, [9,10,11,12] 전체를 z -> (?,?,3,4)     - [1,2,3,4], [5,6,7,8], [9,10,11,12] 전체로 봄(이런게 2개) -> (?,2,3,4)  
    - [[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]] 전체 -> (1,2,3,4)  


3. Axis(밑에 참고하면서 보면 편함)  
    - rank가 4라서 축이 4개가 있다고 봄  
    - 각 축에 번호를 매김.  
    - axis = 3(제일 안쪽에 있는 축, 0부터 시작하니깐 0,1,2,3) or axis = -1  
    - axis = 2
    - axis = 1
    - axis = 0
    

In [12]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS multiply

In [16]:
matrix1 = tf.constant([[1.,2.],[3.,4.]]) # shape : (2,2)
matrix2 = tf.constant([[1.],[2.]]) # shape : (2,1)
print("Metrix 1 shape",matrix1.shape)
print("Metrix 2 shape",matrix2.shape)
tf.matmul(matrix1,matrix2).eval() # matrix 곱을 할 때 (?,*), (*,!) *가 같아야 함 

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [17]:
(matrix1*matrix2).eval() # 일반 곱하기, 위의 행렬 곱과 다름 (조심!!)

array([[1., 2.],
       [6., 8.]], dtype=float32)

## Watch out broadcasting  
- shape이 달라도 연산을 할 수 있게 해주는 것이 broadcasting

In [19]:
matrix1 = tf.constant([[3.,3.]])
matrix2 = tf.constant([[2.,2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

In [20]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.) # 여기를 [[3,3]] 이렇게 만들어줌
(matrix1+matrix2).eval()

array([[4., 5.]], dtype=float32)

In [21]:
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([3.,4.])
(matrix1+matrix2).eval()

array([[4., 6.]], dtype=float32)

In [22]:
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([[3.],[4.]])
(matrix1+matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

## Random values for variable initializations

In [15]:
tf.random_normal([3]).eval() # 랜덤 정규 분포

array([-2.0558274 , -0.86903524, -0.7997548 ], dtype=float32)

In [16]:
tf.random_uniform([2]).eval() # 랜덤 균일 분포

array([0.3966707 , 0.03521109], dtype=float32)

In [17]:
tf.random_uniform([2,3]).eval()

array([[0.74083555, 0.88569283, 0.4511981 ],
       [0.04058504, 0.09051228, 0.5818862 ]], dtype=float32)

**reduce mean**

In [20]:
tf.reduce_mean([1,2],axis=0).eval()

1

In [21]:
x = [[1.,2.], # float
    [3.,4.]]

tf.reduce_mean(x).eval() # 축없이 쓰면 모든 값의 평균

2.5

In [22]:
tf.reduce_mean(x,axis=0).eval() # 2 : 1과 3의 평균, 3: 2와 4의 평균

array([2., 3.], dtype=float32)

In [24]:
tf.reduce_mean(x,axis=1).eval() # 1.5 : 1과 2의 평균, 3.5 : 3과 4의 평균

array([1.5, 3.5], dtype=float32)

In [25]:
tf.reduce_mean(x,axis=-1).eval()

array([1.5, 3.5], dtype=float32)

**reduce sum**

In [26]:
tf.reduce_sum(x).eval()

10.0

In [27]:
tf.reduce_sum(x,axis=0).eval()

array([4., 6.], dtype=float32)

In [28]:
tf.reduce_sum(x,axis=0).eval()

array([4., 6.], dtype=float32)

In [29]:
tf.reduce_sum(x,axis=-1).eval()

array([3., 7.], dtype=float32)

In [30]:
tf.reduce_mean(tf.reduce_sum(x,axis=-1)).eval()

5.0

## Argmax with axis

In [31]:
x = [[0,1,2],
    [2,1,0]]
tf.argmax(x,axis=0).eval()

array([1, 0, 0], dtype=int64)

In [32]:
tf.argmax(x,axis=1).eval() # [0,1,2] 중 가장 큰 것의 위치와 [2,1,0] 중 가장 큰 것의 위치

array([2, 0], dtype=int64)

In [33]:
tf.argmax(x,axis=-1).eval()

array([2, 0], dtype=int64)

## Reshape, squueze, expand_dims

In [34]:
t = np.array([[[0,1,2],
              [3,4,5]],
             [[6,7,8],
             [9,10,11]]])
t.shape

(2, 2, 3)

In [35]:
tf.reshape(t,shape=[-1,3]).eval() # 보통 안 쪽의 값 3은 안 건드림

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
tf.reshape(t,shape=[-1,1,3]).eval() # rank를 더 늘림

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [38]:
tf.squeeze([[0],[1],[2]]).eval() # 쫙 펴줌

array([0, 1, 2])

In [25]:
tf.expand_dims([0,1,2],1).eval() # 2번째 차원을 추가하여 확장

array([[0],
       [1],
       [2]])

## One hot

In [41]:
# [0] : 1번째 자리만 1
# [1] : 2번째 자리만 1
# depth=3 : [1.,0.,0.] 3개
# one hot이 자동적으로 rank를 하나 더 확장(2->3)
tf.one_hot([[0],[1],[2],[0]],depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [45]:
t = tf.one_hot([[0],[1],[2],[0]],depth=3)
tf.reshape(t, shape=[-1,3]).eval() # rank를 2로               

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## casting

In [46]:
tf.cast([1.8,2.2,3.3,4.9],tf.int32).eval() # int로 변환

array([1, 2, 3, 4])

In [47]:
tf.cast([True,False,1==1,0==1],tf.int32).eval() # Boolean형태인 경우 True이면 1, False이면 0을 출력

array([1, 0, 1, 0])

## Stack

In [26]:
x=[1,4]
y=[2,5]
z=[3,6]

# Pack along first dim
tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
tf.stack([x,y,z],axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
tf.stack([x,y,z],axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
tf.stack([x,y,z],axis=-1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like and Zeros like

In [50]:
x = [[0,1,2],
    [2,1,0]]

tf.ones_like(x).eval() # 똑같은 모양인데 1로 채워짐

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
tf.zeros_like(x).eval() # 똑같은 모양인데 0으로 채워짐

array([[0, 0, 0],
       [0, 0, 0]])

## Zip

In [52]:
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [53]:
for x,y,z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9


## Transpose

In [54]:
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [55]:
t1 = tf.transpose(t,[1,0,2]) # [0,1,2] -> [1,0,2] 
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [56]:
t = tf.transpose(t1,[1,0,2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [57]:
t2 = tf.transpose(t,[1,2,0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [58]:
t = tf.transpose(t2,[2,0,1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


### tf.transpose(a, perm=None, name='transpose') 


a를 전치하고 perm에 따라 차원의 순서를 구성한다.

반환되는 텐서의 차원 i는 입력되는 텐서의 차원 perm[i]에 해당한다. 만약 perm이 주어지지 않을 경우, (n-1...0)으로 설정된다. 여기서 n은 입력 텐서의 랭크(rank)이다. 따라서, 기본적으로 이 함수는 2-D 텐서가 입력될 경우 일반적인 행렬 전치를 수행한다다.  


인자:
   - a: Tensor.
   - perm: a의 차원들의 순열.
   - name: 오퍼레이션의 명칭. (선택사항)


반환값: 전치된 Tensor.  


출처 : https://tensorflowkorea.gitbooks.io/tensorflow-kr/content/g3doc/api_docs/python/array_ops.html


In [49]:
x = tf.constant([[1,2,3],
             [4,5,6]])

tf.transpose(x)
#pp.pprint(sess.run(t1))

# perm의 기본값과 동일한 경우
tf.transpose(x,perm=[1,0])

'''
[[1 4]
[2 5]
[3 6]]
'''

'\n[[1 4]\n[2 5]\n[3 6]]\n'

In [40]:
# 'perm'은 차원이 n > 2인 텐서일 경우 더 유용

x = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]]])

# 차원-0의 행렬들에 대해서 전치를 수행
tf.transpose(x, perm=[0, 2, 1]) 

'''
[[[1  4]
[2  5]
[3  6]]

[[7 10]
[8 11]
[9 12]]]
'''

'\n[[[1  4]\n[2  5]\n[3  6]]\n\n[[7 10]\n[8 11]\n[9 12]]]\n'